---
layout: post
title: Blogging Like a Hacker
---
.........
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: what the duck .
......
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle
-----
show_excerpts: true # set to false to remove excerpts on the homepage
....
theme: matejko
.......
